var apiUrl =
  "https://github.com/JimR21/nordvpn-gui/blob/master/mypkg/nord_api.py";

var servers = [
  {
    id: 590778,
    ip_address: "209.58.133.169",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #355",
    domain: "us355.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 37.769813499999998,
      long: -122.46600050000001,
    },
    load: 40,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 590779,
    ip_address: "209.58.133.170",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #356",
    domain: "us356.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 37.769813499999998,
      long: -122.46600050000001,
    },
    load: 64,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 590774,
    ip_address: "162.210.198.131",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #351",
    domain: "us351.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 38.750833299999996,
      long: -77.475555600000007,
    },
    load: 43,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: false,
      proxy_ssl_cybersec: false,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 590775,
    ip_address: "162.210.198.132",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #352",
    domain: "us352.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 38.750833299999996,
      long: -77.475555600000007,
    },
    load: 26,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: false,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 590776,
    ip_address: "209.58.133.167",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #353",
    domain: "us353.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 37.769813499999998,
      long: -122.46600050000001,
    },
    load: 68,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 590777,
    ip_address: "209.58.133.168",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #354",
    domain: "us354.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 37.769813499999998,
      long: -122.46600050000001,
    },
    load: 31,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 590778,
    ip_address: "209.58.133.169",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #355",
    domain: "us355.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 37.769813499999998,
      long: -122.46600050000001,
    },
    load: 40,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 590779,
    ip_address: "209.58.133.170",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #356",
    domain: "us356.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 37.769813499999998,
      long: -122.46600050000001,
    },
    load: 64,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 618584,
    ip_address: "209.58.144.227",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #5032",
    domain: "us5032.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 32.783333300000002,
      long: -96.799999999999997,
    },
    load: 60,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: false,
      proxy: false,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: false,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 727767,
    ip_address: "181.215.110.136",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #502",
    domain: "us502.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 41.850000000000001,
      long: -87.650000000000006,
    },
    load: 80,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 727769,
    ip_address: "181.215.110.137",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #503",
    domain: "us503.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 41.850000000000001,
      long: -87.650000000000006,
    },
    load: 100,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 727771,
    ip_address: "181.215.110.138",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #504",
    domain: "us504.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 41.850000000000001,
      long: -87.650000000000006,
    },
    load: 27,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 727773,
    ip_address: "181.215.110.139",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #505",
    domain: "us505.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 41.850000000000001,
      long: -87.650000000000006,
    },
    load: 52,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 727787,
    ip_address: "181.215.110.148",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "United States #5036",
    domain: "us5036.nordvpn.com",
    price: 0,
    flag: "US",
    country: "United States",
    location: {
      lat: 41.850000000000001,
      long: -87.650000000000006,
    },
    load: 60,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: false,
      proxy: false,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: false,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 727871,
    ip_address: "185.38.150.116",
    search_keywords: [],
    categories: [
      {
        name: "Standard VPN servers",
      },
    ],
    name: "United Kingdom #73",
    domain: "uk73.nordvpn.com",
    price: 0,
    flag: "GB",
    country: "United Kingdom",
    location: {
      lat: 51.514125,
      long: -0.093688999999999995,
    },
    load: 60,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 920769,
    ip_address: "196.196.244.3",
    search_keywords: ["sha512", "P2P"],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "Sweden #60",
    domain: "se60.nordvpn.com",
    price: 0,
    flag: "SE",
    country: "Sweden",
    location: {
      lat: 59.333333000000003,
      long: 18.050000000000001,
    },
    load: 29,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 920771,
    ip_address: "196.196.244.4",
    search_keywords: ["sha512", "P2P"],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "Sweden #61",
    domain: "se61.nordvpn.com",
    price: 0,
    flag: "SE",
    country: "Sweden",
    location: {
      lat: 59.333333000000003,
      long: 18.050000000000001,
    },
    load: 28,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
  {
    id: 920773,
    ip_address: "196.196.244.5",
    search_keywords: ["sha512", "P2P"],
    categories: [
      {
        name: "Standard VPN servers",
      },
      {
        name: "P2P",
      },
    ],
    name: "Sweden #62",
    domain: "se62.nordvpn.com",
    price: 0,
    flag: "SE",
    country: "Sweden",
    location: {
      lat: 59.333333000000003,
      long: 18.050000000000001,
    },
    load: 31,
    features: {
      ikev2: true,
      openvpn_udp: true,
      openvpn_tcp: true,
      socks: true,
      proxy: true,
      pptp: false,
      l2tp: false,
      openvpn_xor_udp: false,
      openvpn_xor_tcp: false,
      proxy_cybersec: true,
      proxy_ssl: true,
      proxy_ssl_cybersec: true,
      ikev2_v6: false,
      openvpn_udp_v6: false,
      openvpn_tcp_v6: false,
      wireguard_udp: false,
      openvpn_udp_tls_crypt: false,
      openvpn_tcp_tls_crypt: false,
      openvpn_dedicated_udp: false,
      openvpn_dedicated_tcp: false,
      v2ray: false,
    },
  },
];
